### ISSUE TITLE
Use pg-promise conversion helpers

### ISSUE THREAD

**Issue by jmeas** [jmeas/finance-app#113]
[These](https://github.com/vitaly-t/pg-promise#conversion-helpers) are convenient

**Comment by vitaly-t** [comment]
Their [API version](http://vitaly-t.github.io/pg-promise/formatting.html) is now better documented ;)

**Comment by jmeas** [comment]
Nice! I'll reference that page as well.

**Comment by jmeas** [comment]
Done!
