### ISSUE TITLE
pg-promise & TypeScript

### ISSUE THREAD

**Issue by vitaly-t** [jmeas/finance-app#168]
I have noticed that you are using `pg-promise` from TypeScript files.

I have never been a fan of TypeScript myself, but many developers who use the library do use TypeScript a lot. You may have noticed that the latest version of the library includes folder `\typescript` where I placed all of the ambient declaration for the library that I could think of.

I do not know how sufficient it is, as I am not proficient enough in TypeScript.

As I understand, you are using something esle to access the library with TypeScript.

I was hoping you would share your experience on the matter.

Also, I asked a question here: http://stackoverflow.com/questions/36526881/exposing-a-node-js-library-via-ambient-typescript

**Comment by jmeas** [comment]
Hmmm...I haven't used TypeScript myself, so I'm not sure if I could help!

**Comment by vitaly-t** [comment]
Is this not TypeScript? - https://github.com/jmeas/finance-app/blob/master/test/integration/api/utils/concatenate-inserts.js

**Comment by vitaly-t** [comment]
Oh I'm starting ti pick up that's some Babel stuff,...feeling dumb now... sorry :)

**Comment by jmeas** [comment]
No worries! Yeah, Babel transpiled code looks whack when coming from ES5.

I'm vaguely interested in TypeScript, but haven't taken the plunge to try it out on a project. If I do, I'll be sure to give ya some feedback on using pgp with it ✌️

**Comment by vitaly-t** [comment]
Just for the future, [TypeScripts for pg-promise](https://github.com/vitaly-t/pg-promise/tree/master/typescript) have been fully finished, and they are kick-ass, so much fun seeing complete interface at design time :)
