### ISSUE TITLE
Refactor to use pg-promise

### ISSUE THREAD

**Issue by jmeas** [jmeas/finance-app#88]
~~[Maybe?](https://github.com/vitaly-t/pg-promise)~~

**Yup!** This will make it easier to build a little abstraction for the API endpoints (promise chaining is easier than setting up cb hell chaining), and I loooove [this feature](https://github.com/vitaly-t/pg-promise#named-parameters).

**Comment by vitaly-t** [comment]
Why not? :)

**Comment by jmeas** [comment]
Haha. I think I'm going to!

**Comment by jmeas** [comment]
Wow, I've begun doing this, and I must say, @vitaly-t, `pg-promise` is truly awesome. Thanks for the awesome library!

**Comment by vitaly-t** [comment]
You are welcome! :)
